# based on convnext 
batch_size: 256
train_interpolation: 'bicubic'
epochs: 300
opt: 'adamw'
opt_eps: 1e-8
opt_betas:
  - 0.9
  - 0.999
momentum: 0.9
weight_decay: 0.05
lr_base: 4e-3 # base lr,  which will be auto-scaled: lr * batch size * nb_gpus / lr_base_size
lr_base_size: 4096 # from convnext
lr_base_scale: 'linear' # linear or sqrt
auto_scale_warmup_min_lr: False
grad_accumulation_steps: 1
min_lr: 1e-6 
sched: 'cosine'
warmup_epochs: 20
warmup_lr: 1e-6  
cooldown_epochs: 0
amp: True
# clip_grad: 5.0
color_jitter: 0.4
smoothing: 0.1
reprob: 0.25
remode: 'pixel'
recount: 1
aa: 'rand-m9-mstd0.5-inc1'
mixup: 0.8
cutmix: 1.0
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'
dist_bn: 'reduce' 
# model_ema: True 
# model_ema_decay: 0.9999
